---
- hosts: prod
  remote_user: ansible
  become: yes
  tasks:
    - name: Installs apache web server
      yum:
        name: httpd
        state: latest # absent
    - name: http service state
      service:
        name: httpd
        state: started
        enabled: yes
