---
#Playbook de instalación de un servidor LAMP mediante roles.
- hosts: prod
  remote_user: ansible
  become: yes
  tasks:
  - firewalld:
      service: http
      permanent: true
      state: enabled
  roles:
    - role: apache
    - role: mysql
    - role: php

