---
- name: Cambiando hostname
  hostname:
    name: "{{ hname }}"

- name: Populando hosts
  template:
    src: hosts.j2
    dest: /etc/hosts
    owner: root
    group: root
    mode: 0644

- name: Include OS-specific variables.
  include_vars: "{{ ansible_os_family }}.yml"

- include: setup-RedHat.yml
  when: ansible_os_family == 'RedHat'

- include: setup-Debian.yml
  when: ansible_os_family == 'Debian'

- name: Creando directorios de brick
  file:
    path: "{{ gluster_brick }}"
    state: directory
    mode: 0775

##Compruebo si ya se ha creado volumenes y guardo el resultado en una variable
#- name: Comprobando si ya hay volumenes creados
#  shell: "gluster volume info"
#  changed_when: false
#  register: gluster_volume_info
#
##Si no existen volumenes conecto los peers entre ellos
#- name: Conectando los peers
#  shell: "gluster peer probe {{ item }}"
#  register: gluster_peer_probe
#  changed_when: "'already in peer list' not in gluster_peer_probe.stdout"
#  failed_when: false
#  with_items: groups.gluster
#  when: "'Volume Name: gluster' not in gluster_volume_info.stdout"

- name: Configurando volumenes
  gluster_volume:
    name: "{{ gluster_volume }}"
    bricks: "{{ gluster_brick }}"
    state: present
    replicas: 2
    cluster: "{{ groups.gluster | join(',') }}"
    force: yes
  run_once: true

